### ISSUE TITLE
[question] sample query for dashboard

### ISSUE THREAD

**Issue by nautilus28** [aphyr/riemann-dash#101]
Hello,

I just spent a day to look at Riemann, I really like it. But with riemann-dash, I'm stuck with querying the streams to make some statistics. Does anyone have a config to achieve some kind of useful dashboards similar to this http://riemann.io/dashboard.html.

Thanks in advance,
Canh

**Comment by faxm0dem** [comment]
What exactly do you need help for:

* query syntax
* keyboard shortcuts for editing riemann-dash
* something else

?

**Comment by nautilus28** [comment]
I need a query sample for hstack/vstack or grid to able able to achieve a dashboard like this picture: http://riemann.io/images/dash-riemann.png.

Thanks

**Comment by faxm0dem** [comment]
You can achieve this interactively by ctrl-clicking on the interface then using keystrokes documented on the default view

**Comment by nautilus28** [comment]
@faxm0dem thank you so much.
